name: PROD - Build and deploy Node.js app to Azure Web App - (careerVest)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0FB1F6B0CE744BEF806D83B4FA37EE3D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B4C3C7EFE03A41858B346F1763A55DA0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FAA9CBEF3ECF4AFDAFA361B6887922BE }}

      - name: Deploy to Azure Web App with Oryx
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'careerVest'
          slot-name: 'Production'
          package: '.'